[start]
cmd = "sleep 30 && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=$PORT"
