[start]
cmd = "php artisan config:clear && php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[build]
cmd = "composer install --no-dev --optimize-autoloader && npm run build"
