[phases.build]
cmd = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"

[phases.setup]
cmd = "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache"

[start]
cmd = "php artisan config:clear && sleep 15 && php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.2"
